# Generated by Django 5.2.4 on 2025-07-29 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(choices=[('europe', 'Europe'), ('asia', 'Asia'), ('america', 'America'), ('africa', 'Africa'), ('australia', 'Australia')], max_length=10)),
                ('departure_date', models.DateField()),
                ('return_date', models.DateField()),
                ('adults', models.IntegerField()),
                ('children', models.IntegerField()),
                ('tour', models.CharField(choices=[('adventure', 'Adventure'), ('cultural', 'Cultural'), ('relaxation', 'Relaxation'), ('family', 'Family'), ('luxury', 'Luxury')], max_length=10)),
            ],
        ),
    ]
